import Rafiul from "./Rafiul.png"
import Logo from "./Logo.png"
import JavaScriptLogo from "./JavaScript Icon.png"
import HtmlLogo from "./HTML Icon.png"
import CSSLogo from "./CSS Icon.png"
import ReactLogo from "./React Icon.png"
import NodeJSLogo from "./Node Js Icon.png"
import TailwindCSSLogo from "./TailWindCSS Icon.png"
import G3ArchitectsLogo from "./G3 Architects.png"
import GymBaranLogo from "./Gym Baran.png"
import DewillingLogo from "./Dewilling.png"
import Services1 from "./Services 1.png"
import Services2 from "./Services 2.png"
import Services3 from "./Services 3.png"

export { Rafiul, Logo, HtmlLogo, CSSLogo, JavaScriptLogo, ReactLogo, TailwindCSSLogo, NodeJSLogo, G3ArchitectsLogo, GymBaranLogo, DewillingLogo, Services1, Services2, Services3 }